/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as LabRouteImport } from './routes/lab'
import { Route as ApiTalkRouteImport } from './routes/api/talk'
import { Route as ApiWarmRouteImport } from './routes/api/warm'
import { Route as ApiCronBrainRouteImport } from './routes/api/cron/brain'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTalkRoute = ApiTalkRouteImport.update({
  id: '/api/talk',
  path: '/api/talk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarmRoute = ApiWarmRouteImport.update({
  id: '/api/warm',
  path: '/api/warm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBrainRoute = ApiCronBrainRouteImport.update({
  id: '/api/cron/brain',
  path: '/api/cron/brain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diary': typeof DiaryRoute
  '/lab': typeof LabRoute
  '/api/talk': typeof ApiTalkRoute
  '/api/warm': typeof ApiWarmRoute
  '/api/cron/brain': typeof ApiCronBrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diary': typeof DiaryRoute
  '/lab': typeof LabRoute
  '/api/talk': typeof ApiTalkRoute
  '/api/warm': typeof ApiWarmRoute
  '/api/cron/brain': typeof ApiCronBrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diary': typeof DiaryRoute
  '/lab': typeof LabRoute
  '/api/talk': typeof ApiTalkRoute
  '/api/warm': typeof ApiWarmRoute
  '/api/cron/brain': typeof ApiCronBrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/diary' | '/lab' | '/api/talk' | '/api/warm' | '/api/cron/brain'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diary' | '/lab' | '/api/talk' | '/api/warm' | '/api/cron/brain'
  id:
    | '__root__'
    | '/'
    | '/diary'
    | '/lab'
    | '/api/talk'
    | '/api/warm'
    | '/api/cron/brain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiaryRoute: typeof DiaryRoute
  LabRoute: typeof LabRoute
  ApiTalkRoute: typeof ApiTalkRoute
  ApiWarmRoute: typeof ApiWarmRoute
  ApiCronBrainRoute: typeof ApiCronBrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/talk': {
      id: '/api/talk'
      path: '/api/talk'
      fullPath: '/api/talk'
      preLoaderRoute: typeof ApiTalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warm': {
      id: '/api/warm'
      path: '/api/warm'
      fullPath: '/api/warm'
      preLoaderRoute: typeof ApiWarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/brain': {
      id: '/api/cron/brain'
      path: '/api/cron/brain'
      fullPath: '/api/cron/brain'
      preLoaderRoute: typeof ApiCronBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiaryRoute: DiaryRoute,
  LabRoute: LabRoute,
  ApiTalkRoute: ApiTalkRoute,
  ApiWarmRoute: ApiWarmRoute,
  ApiCronBrainRoute: ApiCronBrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
